spring.application.name=posts-service

server.servlet.context-path=/posts
server.port = 9010

spring.datasource.url=${POSTS_DB_URL:jdbc:postgresql://localhost:5432/postsDB}
spring.datasource.username=${POSTS_DB_USERNAME:postgres}
spring.datasource.password=${POSTS_DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone= ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}