spring.datasource.url=jdbc:postgresql://posts-db:5432/postsDB
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.kafka.bootstrap-servers=kafka:9092

spring.ai.openai.api-key=${OPENAI_API_KEY}

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

POSTS_SERVICE_URI=http://posts-service
